# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "760ed4dd6f7b9904c8701d284adb8d80"
name = "fajr-app"
application_url = "https://duty-cart-matthew-decision.trycloudflare.com"
embedded = true
handle = "fajr-app"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts"

[auth]
redirect_urls = [
  "https://duty-cart-matthew-decision.trycloudflare.com/auth/callback",
  "https://duty-cart-matthew-decision.trycloudflare.com/auth/shopify/callback",
  "https://duty-cart-matthew-decision.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
